name: Issue Feedback/Feature Request
description: Feedback issues or feature requests
title: "Issue Feedback/Feature Request"
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Ensure the following information
      description: Please confirm the following information
      options:
        - label: When reporting a bug, please attach the complete log.
          required: true
        
        - label: To get instructions on how to retrieve log files in version 0.16.1 and later, use `tsukimi -h`.
          required: true

        - label: Duplicated issues will be closed.
          required: true

        - label: Please make sure you have read the FAQ and pinned issues before submitting.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe the problem you encountered in detail
    validations:
      required: true
